# Python Code Quality Check - Caller Workflow Template
#
# Copy this file to your repository at .github/workflows/code-quality.yml
# This calls the reusable python-code-quality-v2 workflow from srp-actions.
#
# Required secrets (set in your repo or org settings):
#   - FEISHU_CUSTOMERBOT_WEBHOOK: Feishu bot webhook URL
#   - FEISHU_CUSTOMERBOT_SECRET: Feishu bot webhook secret
#   - GH_RELEASE_TOKEN: GitHub PAT for accessing internal packages
#
# Required files in your repository:
#   - requirements.txt: Python dependencies
#   - tests/: Directory containing pytest test files
#
# Optional files:
#   - requirements-dev.txt: Dev/test dependencies (installed if present)
#   - pyproject.toml or ruff.toml: Ruff configuration
#   - pyrightconfig.json: Pyright configuration
#
name: Code Quality

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, develop]

jobs:
  code-quality:
    uses: SerendipityOneInc/srp-actions/.github/workflows/python-code-quality-v2.yml@main
    with:
      python_version: '3.10'
      repo_name: ${{ github.event.repository.name }}
      # Uncomment and customize as needed:
      # ruff_config_file: 'pyproject.toml'
      # pyright_config_file: 'pyrightconfig.json'
      # enable_coverage: true
      # coverage_threshold: '80'
      # coverage_source: 'app'
    secrets:
      FEISHU_CUSTOMERBOT_WEBHOOK: ${{ secrets.FEISHU_CUSTOMERBOT_WEBHOOK }}
      FEISHU_CUSTOMERBOT_SECRET: ${{ secrets.FEISHU_CUSTOMERBOT_SECRET }}
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
