name: doks-statefulset
description: "Deploy StatefulSet to DOKS (Digital Ocean Kubernetes)"

inputs:
  digitalocean_token:
    type: string
    required: true
    description: "Digital Ocean API token"
  doks_cluster_id:
    type: string
    required: true
    description: "DOKS cluster ID"
  doks_namespace:
    description: "namespace of the service/pod to deploy"
    type: string
    required: true
    default: "default"
  statefulset_name:
    type: string
    required: true
  should_export_env:
    description: "whether to export env file"
    type: boolean
    required: false
    default: true
  image_to_deploy:
    description: "image name to deploy"
    type: string
    required: false
  image_tag_to_deploy:
    description: "image tag to deploy"
    type: string
    required: false
  repo_name:
    type: string
    required: false
  env_file:
    type: string
    required: false
  rollout_timeout:
    type: string
    description: "kubectl rollout timeout"
    require: false
    default: "10m"
  environment:
    type: string
    default: "dev"
    description: "Environment"
    required: false
  kustomize_base:
    type: string
    description: "Path to the kustomize directory"
    required: false
    default: "kustomize"
  FEISHU_CUSTOMERBOT_WEBHOOK:
    description: "Feishu customer bot webhook"
    type: string
    required: true
  FEISHU_CUSTOMERBOT_SECRET:
    description: "Feishu customer bot secret"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install doctl CLI
      shell: bash
      run: |
        # Install doctl CLI
        wget https://github.com/digitalocean/doctl/releases/download/v1.101.0/doctl-1.101.0-linux-amd64.tar.gz
        tar xf doctl-1.101.0-linux-amd64.tar.gz
        sudo mv doctl /usr/local/bin
        doctl version

    - name: Configure doctl CLI
      shell: bash
      run: |
        # Authenticate with Digital Ocean
        echo "${{ inputs.digitalocean_token }}" > /tmp/do_token
        doctl auth init --access-token "$(cat /tmp/do_token)" --context default
        doctl auth list

    - name: Verify doctl CLI
      shell: bash
      run: |
        doctl version
        doctl account get

    - name: Configure Kubectl for DOKS
      shell: bash
      run: |
        # Get kubeconfig for the DOKS cluster
        doctl kubernetes cluster kubeconfig save ${{ inputs.doks_cluster_id }}

        # Verify kubectl configuration
        kubectl config current-context
        kubectl cluster-info

    - name: Run Kubectl
      shell: bash
      run: |
        kubectl config view
        kubectl cluster-info
        kubectl get nodes -A
        kubectl get statefulset -n ${{ inputs.doks_namespace }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}

    - id: "export-env"
      name: "Export env file"
      shell: bash
      run: |
        if [[ "${{ inputs.should_export_env }}" == "true" ]]; then
          cat ${{ inputs.env_file }} | base64 > ${{ inputs.repo_name }}.base64
          env_content=$(cat ${{ inputs.repo_name }}.base64 | tr -d '\n')
          echo "env_content=${env_content}" >> $GITHUB_OUTPUT
        fi

    - id: "update-k8s-env-secret"
      name: "Update k8s env secret"
      shell: bash
      run: |
        if [[ "${{ inputs.should_export_env }}" == "true" ]]; then
          kubectl create secret generic ${{ inputs.repo_name }}-env-secret \
            --from-env-file=${{ inputs.env_file }} \
            --namespace=${{ inputs.doks_namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -
        fi

    - id: "kustomize-deploy"
      name: "Deploy to DOKS k8s"
      shell: bash
      run: |
        cd ${{ inputs.kustomize_base }}/overlays/${{ inputs.environment }}
        if [[ "${{ inputs.should_export_env }}" == "true" ]]; then
          echo "using kustomize edit to set image"
          kustomize edit set image ${{ inputs.image_to_deploy }}=${{ inputs.image_tag_to_deploy }}
        fi

        # Check if the StatefulSet exists
        if kubectl get statefulset/${{ inputs.statefulset_name }} -n ${{ inputs.doks_namespace }} > /dev/null 2>&1; then
          echo "StatefulSet ${{ inputs.statefulset_name }} exists. Updating..."
          
          # Apply kustomize and patch the StatefulSet with the env secret version
          kubectl apply -k . -n ${{ inputs.doks_namespace }} || {
            echo "Failed to apply kustomize"
            exit 1
          }
          
          env_secret_version="$(kubectl get secret ${{ inputs.repo_name }}-env-secret -n ${{ inputs.doks_namespace }} -o jsonpath='{.metadata.resourceVersion}')"
          release_time="$(date -Iseconds)"
          kubectl patch statefulset/${{ inputs.statefulset_name }} -n ${{ inputs.doks_namespace }} -p "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"env_secret_version\": \"${env_secret_version}\", \"release_time\": \"${release_time}\"}}}}}"
          
        else
          echo "StatefulSet ${{ inputs.statefulset_name }} does not exist in namespace ${{ inputs.doks_namespace }}. This is the first time deploying."
          kubectl apply -k . -n ${{ inputs.doks_namespace }}
        fi

        # Using StatefulSet rollout status instead of deployment
        kubectl rollout status statefulset/${{ inputs.statefulset_name }} --timeout ${{ inputs.rollout_timeout }} -n ${{ inputs.doks_namespace }}
        kubectl get services -o wide -n ${{ inputs.doks_namespace }}

    - id: deploy-success-notification
      name: Deploy success notification
      uses: SerendipityOneInc/feishu-actions@main
      with:
        # The custom action has bugs, the with here is useless, just to supress vscode error
        FEISHU_CUSTOMERBOT_WEBHOOK: ${{ inputs.FEISHU_CUSTOMERBOT_WEBHOOK }}
        FEISHU_CUSTOMERBOT_SECRET: ${{ inputs.FEISHU_CUSTOMERBOT_SECRET }}
      env:
        # Following are used for feishu message
        FEISHU_CUSTOMERBOT_WEBHOOK: ${{ inputs.FEISHU_CUSTOMERBOT_WEBHOOK }}
        FEISHU_CUSTOMERBOT_SECRET: ${{ inputs.FEISHU_CUSTOMERBOT_SECRET }}
        MSGTYPE: interactive
        CONTENT: |
          ** 🚀 ${{ inputs.statefulset_name }} deployed to DOKS success! **
          - Image Version: ${{ inputs.image_tag_to_deploy }}
          - Github Event Inputs Ref: ${{ github.event.inputs.ref }}
          - DOKS Cluster ID: ${{ inputs.doks_cluster_id }}
          - DOKS Namespace: ${{ inputs.doks_namespace }}
          - Trigger By: ${{ github.event_name	}}
          - Github Ref: ${{ github.ref }}

    - id: deploy-failure-notification
      name: Deploy failure notification
      uses: SerendipityOneInc/feishu-actions@main
      if: failure()
      with:
        # The custom action has bugs, the with here is useless, just to supress vscode error
        FEISHU_CUSTOMERBOT_WEBHOOK: ${{ inputs.FEISHU_CUSTOMERBOT_WEBHOOK }}
        FEISHU_CUSTOMERBOT_SECRET: ${{ inputs.FEISHU_CUSTOMERBOT_SECRET }}
      env:
        # Following are used for feishu message
        FEISHU_CUSTOMERBOT_WEBHOOK: ${{ inputs.FEISHU_CUSTOMERBOT_WEBHOOK }}
        FEISHU_CUSTOMERBOT_SECRET: ${{ inputs.FEISHU_CUSTOMERBOT_SECRET }}
        MSGTYPE: interactive
        CONTENT: |
          ** ❌ ${{ inputs.statefulset_name }} deployed to DOKS failed! **
          - Image Version: ${{ inputs.image_tag_to_deploy }}
          - Github Event Inputs Ref: ${{ github.event.inputs.ref }}
          - DOKS Cluster ID: ${{ inputs.doks_cluster_id }}
          - DOKS Namespace: ${{ inputs.doks_namespace }}
          - Trigger By: ${{ github.event_name	}}
          - Github Ref: ${{ github.ref }}
