name: update-k8s-secret 

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      env_file_base64:
        required: true
        type: string
      deploy_clusters:
        required: true
        type: string
      gke_namespace:
        required: true
        type: string
    secrets:
      DEV_DEPLOYMENT_GKE_SA_KEY:
        required: true
      STAGING_DEPLOYMENT_GKE_SA_KEY:
        required: true
      PRODUCTION_DEPLOYMENT_GKE_SA_KEY:
        required: true
      FEISHU_CUSTOMERBOT_WEBHOOK:
        required: true
      FEISHU_CUSTOMERBOT_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deploy_cluster: ${{ fromJson(inputs.deploy_clusters) }}
    environment: ${{ inputs.environment }}
    steps:
      - id: "set-environment-vars"
        name: "Set environment-specific variables"
        run: |
          case "${{ inputs.environment }}" in
            dev)
              echo "GCP_PROJECT=${{ vars.DEV_GCP_PROJECT }}" >> $GITHUB_ENV
              echo "GKE_LOCATION_PRIMARY=${{ vars.DEV_GKE_LOCATION_PRIMARY }}" >> $GITHUB_ENV
              echo "GKE_CLUSTER_PRIMARY=${{ vars.DEV_GKE_CLUSTER_PRIMARY }}" >> $GITHUB_ENV

              ;;
            staging)
              echo "GCP_PROJECT=${{ vars.STAGING_GCP_PROJECT }}" >> $GITHUB_ENV
              echo "GKE_LOCATION_PRIMARY=${{ vars.STAGING_GKE_LOCATION_PRIMARY }}" >> $GITHUB_ENV
              echo "GKE_CLUSTER_PRIMARY=${{ vars.STAGING_GKE_CLUSTER_PRIMARY }}" >> $GITHUB_ENV

              ;;
            production)
              echo "GCP_PROJECT=${{ vars.PRODUCTION_GCP_PROJECT }}" >> $GITHUB_ENV
              echo "GKE_LOCATION_PRIMARY=${{ vars.PRODUCTION_GKE_LOCATION_PRIMARY }}" >> $GITHUB_ENV
              echo "GKE_CLUSTER_PRIMARY=${{ vars.PRODUCTION_GKE_CLUSTER_PRIMARY }}" >> $GITHUB_ENV

              ;;
            *)
              echo "Unsupported environment: ${{ inputs.environment }}"
              exit 1
              ;;
          esac

          IFS='/' read -r LOCATION CLUSTER <<< "${{ matrix.deploy_cluster }}"
          echo "LOCATION=$LOCATION" >> $GITHUB_ENV
          echo "CLUSTER=$CLUSTER" >> $GITHUB_ENV
          echo "REPO_NAME=${{ inputs.repo_name }}" >> $GITHUB_ENV

      - id: "update-gke-secret"
        uses: SerendipityOneInc/srp-actions/gke-secret@main
        with:
          app_name: ${{ inputs.repo_name }}
          env_file_base64: ${{ inputs.env_file_base64 }}
          gcp_project_id: ${{ env.GCP_PROJECT }}
          gke_location: ${{ env.LOCATION }}
          gke_cluster: ${{ env.CLUSTER }}
          gke_namespace: ${{ inputs.gke_namespace }}
          gke_sa_key: ${{ inputs.environment == 'dev' && secrets.DEV_DEPLOYMENT_GKE_SA_KEY || inputs.environment == 'staging' && secrets.STAGING_DEPLOYMENT_GKE_SA_KEY || secrets.PRODUCTION_DEPLOYMENT_GKE_SA_KEY }}
          FEISHU_CUSTOMERBOT_WEBHOOK: ${{ secrets.FEISHU_CUSTOMERBOT_WEBHOOK }}
          FEISHU_CUSTOMERBOT_SECRET: ${{ secrets.FEISHU_CUSTOMERBOT_SECRET }}
          environment: ${{ inputs.environment }}